In [1]:
# import libraries
import pandas as pd
import numpy as np

In [2]:
#read the data
click = pd.read_csv('data/feature_clickstream.csv')

In [5]:
click.head()
#click.info()

,fe_1,fe_2,fe_3,fe_4,fe_5,fe_6,fe_7,fe_8,fe_9,fe_10,...,fe_13,fe_14,fe_15,fe_16,fe_17,fe_18,fe_19,fe_20,Customer_ID,snapshot_date
0,63,118,80,121,55,193,111,112,-101,83,...,-16,-81,-126,114,35,85,-73,76,CUS_0x1037,2023-01-01
1,-108,182,123,4,-56,27,25,-6,284,222,...,-14,-96,200,35,130,94,111,75,CUS_0x1069,2023-01-01
2,-13,8,87,166,214,-98,215,152,129,139,...,26,86,171,125,-130,354,17,302,CUS_0x114a,2023-01-01
3,-85,45,200,89,128,54,76,51,61,139,...,172,96,174,163,37,207,180,118,CUS_0x1184,2023-01-01
4,55,120,226,-86,253,97,107,68,103,126,...,76,43,183,159,-26,104,118,184,CUS_0x1297,2023-01-01

In [4]:
click.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215376 entries, 0 to 215375
Data columns (total 22 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   fe_1           215376 non-null  int64
 1   fe_2           215376 non-null  int64
 2   fe_3           215376 non-null  int64
 3   fe_4           215376 non-null  int64
 4   fe_5           215376 non-null  int64
 5   fe_6           215376 non-null  int64
 6   fe_7           215376 non-null  int64
 7   fe_8           215376 non-null  int64
 8   fe_9           215376 non-null  int64
 9   fe_10          215376 non-null  int64
 10  fe_11          215376 non-null  int64
 11  fe_12          215376 non-null  int64
 12  fe_13          215376 non-null  int64
 13  fe_14          215376 non-null  int64
 14  fe_15          215376 non-null  int64
 15  fe_16          215376 non-null  int64
 16  fe_17          215376 non-null  int64
 17  fe_18          215376 non-null  int64
 18  fe_19          215376 non-null  int64
 19  fe_20          215376 non-null  int64
 20  Customer_ID    215376 non-null  object
 21  snapshot_date  215376 non-null  object
dtypes: int64(20), object(2)
memory usage: 36.2+ MB

In [3]:
# Explore the data
click.describe()

,fe_1,fe_2,fe_3,fe_4,fe_5,fe_6,fe_7,fe_8,fe_9,fe_10,fe_11,fe_12,fe_13,fe_14,fe_15,fe_16,fe_17,fe_18,fe_19,fe_20
count,215376.000000,215376.000000,215376.000000,215376.000000,215376.000000,215376.000000,215376.000000,215376.000000,215376.000000,215376.000000,215376.000000,215376.000000,215376.000000,215376.000000,215376.000000,215376.000000,215376.000000,215376.000000,215376.000000,215376.000000
mean,101.414796,103.096195,104.333709,105.648503,106.996676,103.235922,107.070337,110.718724,114.406354,117.775797,99.615537,99.823680,100.420804,100.025801,99.600383,99.860834,100.129425,100.125139,100.341162,100.046259
std,99.833594,99.930002,100.599865,100.326065,100.693607,100.270388,100.323265,100.243698,100.186139,100.807686,100.335428,100.591175,100.881826,101.070371,101.145906,100.751876,101.298428,102.231587,102.666804,103.589358
min,-378.000000,-356.000000,-399.000000,-307.000000,-343.000000,-321.000000,-368.000000,-361.000000,-328.000000,-317.000000,-375.000000,-344.000000,-355.000000,-394.000000,-351.000000,-342.000000,-329.000000,-344.000000,-401.000000,-354.000000
25%,34.000000,36.000000,36.000000,38.000000,39.000000,36.000000,39.000000,43.000000,47.000000,50.000000,32.000000,32.000000,33.000000,32.000000,31.000000,32.000000,32.000000,31.000000,31.000000,30.000000
50%,102.000000,103.000000,104.000000,106.000000,107.000000,103.000000,107.000000,111.000000,115.000000,118.000000,100.000000,100.000000,101.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
75%,169.000000,171.000000,172.000000,173.000000,175.000000,171.000000,174.000000,179.000000,182.000000,186.000000,167.000000,168.000000,168.000000,168.000000,168.000000,168.000000,169.000000,169.000000,170.000000,170.000000
max,541.000000,560.000000,583.000000,562.000000,570.000000,565.000000,537.000000,573.000000,577.000000,537.000000,613.000000,550.000000,530.000000,583.000000,597.000000,554.000000,516.000000,551.000000,560.000000,547.000000

In [7]:
#check for missing values
click.isnull().sum()

fe_1             0
fe_2             0
fe_3             0
fe_4             0
fe_5             0
fe_6             0
fe_7             0
fe_8             0
fe_9             0
fe_10            0
fe_11            0
fe_12            0
fe_13            0
fe_14            0
fe_15            0
fe_16            0
fe_17            0
fe_18            0
fe_19            0
fe_20            0
Customer_ID      0
snapshot_date    0
dtype: int64

In [11]:
click.isna().mean()

fe_1             0.0
fe_2             0.0
fe_3             0.0
fe_4             0.0
fe_5             0.0
fe_6             0.0
fe_7             0.0
fe_8             0.0
fe_9             0.0
fe_10            0.0
fe_11            0.0
fe_12            0.0
fe_13            0.0
fe_14            0.0
fe_15            0.0
fe_16            0.0
fe_17            0.0
fe_18            0.0
fe_19            0.0
fe_20            0.0
Customer_ID      0.0
snapshot_date    0.0
dtype: float64

In [12]:
#check for duplicates
click.duplicated().sum()

np.int64(0)

In [4]:
#read attributes data
attributes = pd.read_csv('data/features_attributes.csv')

In [5]:
# some basic information about the attributes data
attributes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12500 entries, 0 to 12499
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    12500 non-null  object
 1   Name           12500 non-null  object
 2   Age            12500 non-null  object
 3   SSN            12500 non-null  object
 4   Occupation     12500 non-null  object
 5   snapshot_date  12500 non-null  object
dtypes: object(6)
memory usage: 586.1+ KB

In [6]:

attributes.describe()

       Customer_ID    Name    Age        SSN Occupation snapshot_date
count        12500   12500  12500      12500      12500         12500
unique       12500   10139    301      11798         16            25
top      CUS_0xffd  Langep     26  #F%$D@*&8    _______    2024-08-01
freq             1       6    364        703        880           543

In [7]:

attributes.isnull().sum()

Customer_ID      0
Name             0
Age              0
SSN              0
Occupation       0
snapshot_date    0
dtype: int64

In [20]:
# Check for data types of the columns in the attributes data
attributes.dtypes

Customer_ID      object
Name             object
Age              object
SSN              object
Occupation       object
snapshot_date    object
dtype: object

In [8]:
attributes.head()

  Customer_ID            Name Age          SSN     Occupation snapshot_date
0  CUS_0x1000  Alistair Barrf  18  913-74-1218         Lawyer    2023-05-01
1  CUS_0x1009          Arunah  26  063-67-6938       Mechanic    2025-01-01
2  CUS_0x100b        Shirboni  19    #F%$D@*&8  Media_Manager    2024-03-01
3  CUS_0x1011       Schneyerh  44  793-05-8223         Doctor    2023-11-01
4  CUS_0x1013        Cameront  44  930-49-9615       Mechanic    2023-12-01

In [96]:
attributes[attributes['SSN'] == '#F%$D@*&8']

,Customer_ID,Name,Age,SSN,Occupation,snapshot_date
2,CUS_0x100b,Shirboni,19,#F%$D@*&8,Media_Manager,2024-03-01
9,CUS_0x102e,Rhysn,26,#F%$D@*&8,Scientist,2024-04-01
15,CUS_0x1044,Maki Shirakip,44,#F%$D@*&8,_______,2023-06-01
17,CUS_0x104a,Leahk,37,#F%$D@*&8,Mechanic,2023-12-01
23,CUS_0x105b,Patricia Zengerlel,24,#F%$D@*&8,Accountant,2023-11-01
...,...,...,...,...,...,...
12409,CUS_0xe94,Nishanta,53,#F%$D@*&8,Musician,2024-03-01
12425,CUS_0xecc,Papadimase,25,#F%$D@*&8,Lawyer,2024-11-01
12442,CUS_0xf20,Anurag Kotokyf,41,#F%$D@*&8,Musician,2023-04-01
12446,CUS_0xf30,Hornbyb,29,#F%$D@*&8,Journalist,2023-06-01
12495,CUS_0xff3,Somervilled,55,#F%$D@*&8,Scientist,2024-06-01

In [9]:
# replace Occupation = "_______" with "UnSpecified"
attributes['Occupation'] = attributes['Occupation'].replace('_______', 'UnSpecified')

In [10]:
attributes[attributes['SSN'] == '#F%$D@*&8']

,Customer_ID,Name,Age,SSN,Occupation,snapshot_date
2,CUS_0x100b,Shirboni,19,#F%$D@*&8,Media_Manager,2024-03-01
9,CUS_0x102e,Rhysn,26,#F%$D@*&8,Scientist,2024-04-01
15,CUS_0x1044,Maki Shirakip,44,#F%$D@*&8,UnSpecified,2023-06-01
17,CUS_0x104a,Leahk,37,#F%$D@*&8,Mechanic,2023-12-01
23,CUS_0x105b,Patricia Zengerlel,24,#F%$D@*&8,Accountant,2023-11-01
...,...,...,...,...,...,...
12409,CUS_0xe94,Nishanta,53,#F%$D@*&8,Musician,2024-03-01
12425,CUS_0xecc,Papadimase,25,#F%$D@*&8,Lawyer,2024-11-01
12442,CUS_0xf20,Anurag Kotokyf,41,#F%$D@*&8,Musician,2023-04-01
12446,CUS_0xf30,Hornbyb,29,#F%$D@*&8,Journalist,2023-06-01
12495,CUS_0xff3,Somervilled,55,#F%$D@*&8,Scientist,2024-06-01

In [122]:
# read features financial data
financial = pd.read_csv('data/features_financials.csv')

In [98]:
# some basic information about the financial data
financial.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12500 entries, 0 to 12499
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer_ID               12500 non-null  object
 1   Annual_Income             12500 non-null  object
 2   Monthly_Inhand_Salary     12500 non-null  float64
 3   Num_Bank_Accounts         12500 non-null  int64
 4   Num_Credit_Card           12500 non-null  int64
 5   Interest_Rate             12500 non-null  int64
 6   Num_of_Loan               12500 non-null  object
 7   Type_of_Loan              11074 non-null  object
 8   Delay_from_due_date       12500 non-null  int64
 9   Num_of_Delayed_Payment    12500 non-null  object
 10  Changed_Credit_Limit      12500 non-null  object
 11  Num_Credit_Inquiries      12500 non-null  float64
 12  Credit_Mix                12500 non-null  object
 13  Outstanding_Debt          12500 non-null  object
 14  Credit_Utilization_Ratio  12500 non-null  float64
 15  Credit_History_Age        12500 non-null  object
 16  Payment_of_Min_Amount     12500 non-null  object
 17  Total_EMI_per_month       12500 non-null  float64
 18  Amount_invested_monthly   12500 non-null  object
 19  Payment_Behaviour         12500 non-null  object
 20  Monthly_Balance           12500 non-null  object
 21  snapshot_date             12500 non-null  object
dtypes: float64(4), int64(4), object(14)
memory usage: 2.1+ MB

In [118]:
def inspect_number_values(df):
    #inspect number values columns
    num_cols = df.select_dtypes(include=['object']).columns.tolist()
    for col in num_cols:
        if col in df.columns:
            print(f"Column: {col}")
            valid_number_pattern = r'^[+-]?(?:\d+\.?\d*|\.\d+)$'
            non_numeric_values = df[col][~df[col].str.contains(valid_number_pattern, regex=True, na=False)].unique()
            if len(non_numeric_values) > 0:
                print(f"Non-numeric values in column '{col}': {non_numeric_values}")
            #print(df[col][df[col].str.contains(r'^[+-]?(?:\d+\.?\d*|\.\d+)$', regex=True, na=False)].unique())
            print("\n")

In [ ]:
inspect_number_values(financial)

In [143]:
# read features financial data
financial = pd.read_csv('data/features_financials.csv')

In [144]:
#Clean up data in the financial dataset   
financial['Annual_Income'] = financial['Annual_Income'].str.replace('\..*', '', regex=True).astype(int)   
financial['Monthly_Inhand_Salary'] = (financial['Annual_Income'] / 12).round(2)
financial['Num_of_Loan'] = financial['Num_of_Loan'].str.replace('_', '', regex=True).astype(int).abs()

financial['Num_of_Delayed_Payment'] = financial['Num_of_Delayed_Payment'].str.replace('_', '', regex=True).astype(int).abs()
financial['Changed_Credit_Limit'] = financial['Changed_Credit_Limit'].str.replace('_', '0', regex=True).astype(float)
financial['Outstanding_Debt'] = financial['Outstanding_Debt'].str.replace('_', '', regex=True).astype(float)
financial['Amount_invested_monthly'] = financial['Amount_invested_monthly'].str.replace('_', '', regex=True).astype(float).round(2)
financial['Monthly_Balance'] = financial['Monthly_Balance'].str.replace('_', '', regex=True).round(2).astype(float)
financial['Credit_Utilization_Ratio'] = financial['Credit_Utilization_Ratio'].round(2)
financial['Total_EMI_per_month'] = financial['Total_EMI_per_month'].round(2)
financial['Monthly_Balance'] = financial['Monthly_Balance'].round(2)

In [145]:
# convert '10 years 3 months' to months
def convert_credit_history_age_to_months(age_str):
    if pd.isnull(age_str):
        return np.nan
    years, months = 0, 0
    if 'Years' in age_str:
        years = int(age_str.split('Years')[0].strip())
    if 'Months' in age_str:
        months = int(age_str.split('Months')[0].split()[-1].strip())
    return years * 12 + months

In [146]:
financial['Credit_History_Age_months'] = financial['Credit_History_Age'].apply(convert_credit_history_age_to_months)

In [147]:
financial.head()

,Customer_ID,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,...,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,snapshot_date,Credit_History_Age_months
0,CUS_0x1000,30625,2552.08,6,5,27,2,"Credit-Builder Loan, and Home Equity Loan",57,26,...,1562.91,30.08,10 Years and 9 Months,Yes,42.94,77.31,High_spent_Medium_value_payments,400.36,2023-05-01,129
1,CUS_0x1009,52312,4359.33,6,5,17,4,"Not Specified, Home Equity Loan, Credit-Builde...",5,18,...,202.68,40.29,31 Years and 0 Months,Yes,108.37,58.66,High_spent_Medium_value_payments,508.01,2025-01-01,372
2,CUS_0x100b,113781,9481.75,1,4,1,0,NaN,14,8,...,1030.20,28.59,15 Years and 10 Months,No,0.00,617.08,High_spent_Small_value_payments,597.90,2024-03-01,190
3,CUS_0x1011,58918,4909.83,3,3,17,3,"Student Loan, Credit-Builder Loan, and Debt Co...",27,13,...,473.14,27.83,15 Years and 10 Months,Yes,123.43,383.35,Low_spent_Medium_value_payments,294.10,2023-11-01,190
4,CUS_0x1013,98620,8218.33,3,3,6,3,"Student Loan, Debt Consolidation Loan, and Per...",12,9,...,1233.51,26.52,17 Years and 10 Months,No,228.02,332.33,High_spent_Medium_value_payments,485.89,2023-12-01,214

In [148]:
financial

,Customer_ID,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,...,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,snapshot_date,Credit_History_Age_months
0,CUS_0x1000,30625,2552.08,6,5,27,2,"Credit-Builder Loan, and Home Equity Loan",57,26,...,1562.91,30.08,10 Years and 9 Months,Yes,42.94,77.31,High_spent_Medium_value_payments,400.36,2023-05-01,129
1,CUS_0x1009,52312,4359.33,6,5,17,4,"Not Specified, Home Equity Loan, Credit-Builde...",5,18,...,202.68,40.29,31 Years and 0 Months,Yes,108.37,58.66,High_spent_Medium_value_payments,508.01,2025-01-01,372
2,CUS_0x100b,113781,9481.75,1,4,1,0,NaN,14,8,...,1030.20,28.59,15 Years and 10 Months,No,0.00,617.08,High_spent_Small_value_payments,597.90,2024-03-01,190
3,CUS_0x1011,58918,4909.83,3,3,17,3,"Student Loan, Credit-Builder Loan, and Debt Co...",27,13,...,473.14,27.83,15 Years and 10 Months,Yes,123.43,383.35,Low_spent_Medium_value_payments,294.10,2023-11-01,190
4,CUS_0x1013,98620,8218.33,3,3,6,3,"Student Loan, Debt Consolidation Loan, and Per...",12,9,...,1233.51,26.52,17 Years and 10 Months,No,228.02,332.33,High_spent_Medium_value_payments,485.89,2023-12-01,214
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12495,CUS_0xff3,17032,1419.33,0,6,2,3,"Personal Loan, Mortgage Loan, and Auto Loan",13,7,...,1229.08,26.92,17 Years and 3 Months,No,33.30,81.20,Low_spent_Small_value_payments,293.14,2024-06-01,207
12496,CUS_0xff4,25546,2128.83,8,7,14,5,"Not Specified, Student Loan, Student Loan, Cre...",15,13,...,758.44,39.33,18 Years and 9 Months,Yes,101.33,189.82,Low_spent_Medium_value_payments,230.44,2024-12-01,225
12497,CUS_0xff6,117639,9803.25,5,6,1,2,"Home Equity Loan, and Auto Loan",-3,7,...,338.30,32.87,24 Years and 11 Months,No,126.64,534.09,Low_spent_Medium_value_payments,592.01,2024-10-01,299
12498,CUS_0xffc,60877,5073.08,6,8,27,8,"Credit-Builder Loan, Payday Loan, Not Specifie...",46,14,...,1300.13,29.03,13 Years and 1 Months,Yes,272.81,46.43,High_spent_Large_value_payments,442.57,2024-01-01,157
12499,CUS_0xffd,41398,3449.83,8,7,13,6,"Auto Loan, Payday Loan, Payday Loan, Mortgage ...",23,11,...,1701.88,39.92,18 Years and 9 Months,Yes,182.98,42.58,High_spent_Large_value_payments,389.43,2024-03-01,225

In [149]:
inspect_number_values(attributes)

Column: Customer_ID
Non-numeric values in column 'Customer_ID': ['CUS_0x1000' 'CUS_0x1009' 'CUS_0x100b' ... 'CUS_0xff6' 'CUS_0xffc'
 'CUS_0xffd']


Column: Name
Non-numeric values in column 'Name': ['Alistair Barrf' 'Arunah' 'Shirboni' ... 'Shieldsb' 'Brads' 'Damouniq']


Column: Age
Non-numeric values in column 'Age': ['40_' '46_' '3843_' '30_' '24_' '22_' '32_' '26_' '34_' '41_' '1248_'
 '23_' '43_' '19_' '53_' '18_' '15_' '55_' '50_' '42_' '16_' '27_' '31_'
 '38_' '8669_' '45_' '39_' '17_' '44_' '35_' '29_' '28_' '33_' '21_' '20_'
 '2329_' '5798_' '1070_' '48_' '36_' '37_' '25_' '3834_' '52_' '14_' '54_'
 '49_' '7723_' '47_' '6408_' '3984_' '51_' '6556_' '4301_' '56_' '6744_']


Column: SSN
Non-numeric values in column 'SSN': ['913-74-1218' '063-67-6938' '#F%$D@*&8' ... '541-92-8371' '226-86-7294'
 '832-88-8320']


Column: Occupation
Non-numeric values in column 'Occupation': ['Lawyer' 'Mechanic' 'Media_Manager' 'Doctor' 'Journalist' 'Accountant'
 'Manager' 'Entrepreneur' 'Scientist' 'Architect' 'Teacher' '_______'
 'Engineer' 'Writer' 'Developer' 'Musician']


Column: snapshot_date
Non-numeric values in column 'snapshot_date': ['2023-05-01' '2025-01-01' '2024-03-01' '2023-11-01' '2023-12-01'
 '2023-08-01' '2023-10-01' '2024-01-01' '2024-04-01' '2023-01-01'
 '2024-10-01' '2024-12-01' '2023-06-01' '2024-02-01' '2023-04-01'
 '2023-09-01' '2024-05-01' '2024-11-01' '2024-09-01' '2023-02-01'
 '2024-08-01' '2023-03-01' '2024-06-01' '2024-07-01' '2023-07-01']